import Foundation
import UIKit

protocol AppDataExporting: Sendable { func createExport(includeRecoveryData: Bool) async throws -> URL }
protocol AppDataManaging: Sendable { func loadSummary() async throws -> AppDataSummary; func deleteReceipts() async -> DataDeletionReport; func deleteCalculations() async -> DataDeletionReport; func deleteSplits() async -> DataDeletionReport; func deleteNotes() async -> DataDeletionReport; func clearCurrencyCache() async -> DataDeletionReport; func clearCurrencyFavorites() async -> DataDeletionReport; func clearRecentCurrencyPairs() async -> DataDeletionReport; func clearGuideData() async -> DataDeletionReport; func resetPreferences() async -> DataDeletionReport; func resetOnboarding() async -> DataDeletionReport; func deleteMigrationMarkers() async -> DataDeletionReport; func deleteMigrationBackups() async -> DataDeletionReport; func deleteQuarantinedLegacyData() async -> DataDeletionReport; func deleteTemporaryAndRecoveryFiles() async -> DataDeletionReport; func deleteAllLocalData(includeRecoveryData: Bool) async -> DataDeletionReport }

enum DataCategory: String, Codable, Sendable { case receipts, calculations, splits, notes, currencyCache, currencyFavorites, recentCurrencyPairs, guideData, preferences, onboarding, migrationMarkers, migrationBackups, quarantine, temporaryAndRecoveryFiles }
struct DataDeletionFailure: Codable, Sendable, Hashable { var category: DataCategory; var message: String }
struct DataDeletionReport: Codable, Sendable { var deletedCategories: [DataCategory]; var failures: [DataDeletionFailure]; var completedFully: Bool { failures.isEmpty } }
struct AppDataSummary: Codable, Sendable { var receiptCount: Int; var calculationCount: Int; var splitCount: Int; var noteCount: Int; var guideBookmarkCount: Int; var favoriteCurrencyCount: Int; var recentCurrencyPairCount: Int; var cachedExchangeRateCount: Int; var receiptImageStorage: Int64; var totalAppDataStorage: Int64; var migrationBackupStorage: Int64; var quarantinedSourceCount: Int }
struct AppDataExportManifest: Codable, Sendable { var exportSchemaVersion: Int; var appVersion: String; var buildNumber: String; var exportDate: Date; var includedDataCategories: [String]; var recordCounts: [String:Int]; var missingOptionalImageFiles: [String]; var recoveryDataIncluded: Bool; var exportWarnings: [String] }

actor FileAppDataService: AppDataExporting, AppDataManaging {
    private let root: URL; private let fm: FileManager; private let receipts: ReceiptRepository; private let calculations: CalculationRepository; private let preferences: UserPreferencesRepository; private let defaults: UserDefaults = .standard
    init(rootURL: URL? = nil, fileManager: FileManager = .default, receiptRepository: ReceiptRepository, calculationRepository: CalculationRepository, preferencesRepository: UserPreferencesRepository) { root = rootURL ?? fileManager.urls(for: .documentDirectory, in: .userDomainMask)[0]; fm = fileManager; receipts = receiptRepository; calculations = calculationRepository; preferences = preferencesRepository }
    func createExport(includeRecoveryData: Bool) async throws -> URL {
        let exportRoot = fm.temporaryDirectory.appendingPathComponent("TipsForTipsExport-\(UUID().uuidString)", isDirectory: true).appendingPathComponent("TipsForTipsExport", isDirectory: true)
        try fm.createDirectory(at: exportRoot, withIntermediateDirectories: true)
        let receiptRecords = try await receipts.fetchReceipts(); let calcRecords = try await calculations.fetchCalculations(); let prefs = try await preferences.loadPreferences()
        let enc = JSONEncoder(); enc.outputFormatting = [.prettyPrinted, .sortedKeys]; enc.dateEncodingStrategy = .iso8601
        try enc.encode(prefs).write(to: exportRoot.appendingPathComponent("preferences.json"))
        try enc.encode(receiptRecords).write(to: exportRoot.appendingPathComponent("receipts.json"))
        try enc.encode(calcRecords.filter { $0.tipResult != nil }).write(to: exportRoot.appendingPathComponent("calculations.json"))
        try enc.encode(calcRecords.filter { $0.splitResult != nil }).write(to: exportRoot.appendingPathComponent("saved-splits.json"))
        try copyIfPresent("Notes/notes.json", to: exportRoot.appendingPathComponent("notes.json"), fallbackArrayWith: enc)
        try enc.encode(guideBookmarks()).write(to: exportRoot.appendingPathComponent("guide-bookmarks.json"))
        try enc.encode(guideRecents()).write(to: exportRoot.appendingPathComponent("guide-recents.json"))
        try enc.encode(currencyFavorites()).write(to: exportRoot.appendingPathComponent("currency-favorites.json"))
        try enc.encode(recentCurrencyPairs()).write(to: exportRoot.appendingPathComponent("recent-currency-pairs.json"))
        try copyIfPresent("V2/Currency/rates.json", to: exportRoot.appendingPathComponent("currency-cache.json"), fallbackArrayWith: enc)
        var missing: [String] = []
        let imageDir = exportRoot.appendingPathComponent("receipt-images", isDirectory: true), thumbDir = exportRoot.appendingPathComponent("receipt-thumbnails", isDirectory: true)
        try fm.createDirectory(at: imageDir, withIntermediateDirectories: true); try fm.createDirectory(at: thumbDir, withIntermediateDirectories: true)
        for r in receiptRecords { for (name,dir,srcDir) in [(r.imageFilename,imageDir,"Images"),(r.thumbnailFilename,thumbDir,"Thumbnails")] { guard let name else { continue }; let src = root.appendingPathComponent("V2/Receipts/\(srcDir)/\(name)"); if fm.fileExists(atPath: src.path) { do { try fm.copyItem(at: src, to: dir.appendingPathComponent(name)) } catch { missing.append("\(name): \(error.localizedDescription)") } } else { missing.append(name) } } }
        if includeRecoveryData, fm.fileExists(atPath: root.appendingPathComponent("V2/Backups").path) { try fm.copyItem(at: root.appendingPathComponent("V2/Backups"), to: exportRoot.appendingPathComponent("migration-recovery")) }
        let manifest = AppDataExportManifest(exportSchemaVersion: 1, appVersion: Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String ?? "Unknown", buildNumber: Bundle.main.object(forInfoDictionaryKey: "CFBundleVersion") as? String ?? "Unknown", exportDate: Date(), includedDataCategories: ["preferences","receipts","calculations","saved-splits","notes","guide","currency","receipt-images"], recordCounts: ["receipts": receiptRecords.count, "calculations": calcRecords.filter{$0.tipResult != nil}.count, "splits": calcRecords.filter{$0.splitResult != nil}.count, "notes": countJSON("Notes/notes.json"), "guideBookmarks": guideBookmarks().count, "guideRecents": guideRecents().count, "currencyFavorites": currencyFavorites().count, "recentCurrencyPairs": recentCurrencyPairs().count, "cachedExchangeRates": countJSON("V2/Currency/rates.json")], missingOptionalImageFiles: missing, recoveryDataIncluded: includeRecoveryData, exportWarnings: receiptRecords.flatMap { ReceiptFinancialReviewValidator().review($0).warnings }.isEmpty ? [] : ["Some receipts need financial charge review."])
        try enc.encode(manifest).write(to: exportRoot.appendingPathComponent("export-manifest.json")); return exportRoot
    }
    func loadSummary() async throws -> AppDataSummary { let rs = try await receipts.fetchReceipts(); let cs = try await calculations.fetchCalculations(); return AppDataSummary(receiptCount: rs.count, calculationCount: cs.filter{$0.tipResult != nil}.count, splitCount: cs.filter{$0.splitResult != nil}.count, noteCount: countJSON("Notes/notes.json"), guideBookmarkCount: guideBookmarks().count, favoriteCurrencyCount: currencyFavorites().count, recentCurrencyPairCount: recentCurrencyPairs().count, cachedExchangeRateCount: countJSON("V2/Currency/rates.json"), receiptImageStorage: size("V2/Receipts/Images") + size("V2/Receipts/Thumbnails"), totalAppDataStorage: size("V2"), migrationBackupStorage: size("V2/Backups"), quarantinedSourceCount: countFiles("V2/Backups/Quarantine")) }
    private func ok(_ c: DataCategory) -> DataDeletionReport { DataDeletionReport(deletedCategories: [c], failures: []) }
    private func fail(_ c: DataCategory, _ error: Error) -> DataDeletionReport { DataDeletionReport(deletedCategories: [], failures: [.init(category: c, message: error.localizedDescription)]) }
    private func remove(_ rel: String, _ c: DataCategory) -> DataDeletionReport { do { let u=root.appendingPathComponent(rel); if fm.fileExists(atPath:u.path){try fm.removeItem(at:u)}; return ok(c)} catch { return DataDeletionReport(deletedCategories: [], failures: [.init(category: c, message: error.localizedDescription)]) } }
    func deleteReceipts() async -> DataDeletionReport {
        var failures: [DataDeletionFailure] = []
        do { for r in try await receipts.fetchReceipts() { try await receipts.deleteReceipt(id: r.id) } } catch { failures.append(.init(category: .receipts, message: error.localizedDescription)) }
        for rel in ["V2/Receipts", "Receipts", "receipts.json"] {
            let report = remove(rel, .receipts)
            failures.append(contentsOf: report.failures)
        }
        if failures.isEmpty { _ = remove("V2/migration-v2-complete.json", .migrationMarkers) }
        return DataDeletionReport(deletedCategories: failures.isEmpty ? [.receipts] : [], failures: failures)
    }
    func deleteCalculations() async -> DataDeletionReport { do { for c in (try await calculations.fetchCalculations()).filter({$0.tipResult != nil}) { try await calculations.deleteCalculation(id: c.id) }; return ok(.calculations) } catch { return fail(.calculations, error) } }
    func deleteSplits() async -> DataDeletionReport { do { for c in (try await calculations.fetchCalculations()).filter({$0.splitResult != nil}) { try await calculations.deleteCalculation(id: c.id) }; return ok(.splits) } catch { return fail(.splits, error) } }
    func deleteNotes() async -> DataDeletionReport { remove("Notes", .notes) }; func clearCurrencyCache() async -> DataDeletionReport { remove("V2/Currency/rates.json", .currencyCache) }; func clearCurrencyFavorites() async -> DataDeletionReport { defaults.removeObject(forKey: "currency.favoriteCodes"); return ok(.currencyFavorites) }; func clearRecentCurrencyPairs() async -> DataDeletionReport { defaults.removeObject(forKey: "currency.recentPairs"); return ok(.recentCurrencyPairs) }; func clearGuideData() async -> DataDeletionReport { defaults.removeObject(forKey: "guide.bookmarks"); defaults.removeObject(forKey: "guide.recent"); return ok(.guideData) }; func resetPreferences() async -> DataDeletionReport { do { try await preferences.savePreferences(.defaults); return ok(.preferences) } catch { return fail(.preferences, error) } }; func resetOnboarding() async -> DataDeletionReport { do { var p = try await preferences.loadPreferences(); p.hasCompletedOnboarding = false; try await preferences.savePreferences(p.validated); return ok(.onboarding) } catch { return fail(.onboarding, error) } }; func deleteMigrationMarkers() async -> DataDeletionReport { remove("V2/migration-v2-complete.json", .migrationMarkers) }; func deleteMigrationBackups() async -> DataDeletionReport { remove("V2/Backups", .migrationBackups) }; func deleteQuarantinedLegacyData() async -> DataDeletionReport { remove("V2/Backups/Quarantine", .quarantine) }; func deleteTemporaryAndRecoveryFiles() async -> DataDeletionReport { var reports = [remove("V2/Receipts/Temporary", .temporaryAndRecoveryFiles)]; reports.append(contentsOf: deleteGeneratedExports()); return DataDeletionReport(deletedCategories: reports.flatMap{$0.deletedCategories}.isEmpty ? [] : [.temporaryAndRecoveryFiles], failures: reports.flatMap{$0.failures}) }
    private func deleteGeneratedExports() -> [DataDeletionReport] { ((try? fm.contentsOfDirectory(at: fm.temporaryDirectory, includingPropertiesForKeys: nil)) ?? []).filter { $0.lastPathComponent.hasPrefix("TipsForTipsExport-") }.map { url in do { try fm.removeItem(at: url); return ok(.temporaryAndRecoveryFiles) } catch { return fail(.temporaryAndRecoveryFiles, error) } } }
    func deleteAllLocalData(includeRecoveryData: Bool) async -> DataDeletionReport { var reports = [await deleteReceipts(), await deleteCalculations(), await deleteSplits(), await deleteNotes(), await clearCurrencyCache(), await clearCurrencyFavorites(), await clearRecentCurrencyPairs(), await clearGuideData(), await resetPreferences(), await resetOnboarding(), await deleteTemporaryAndRecoveryFiles()]; if includeRecoveryData { reports += [await deleteMigrationBackups(), await deleteQuarantinedLegacyData()] }; return DataDeletionReport(deletedCategories: reports.flatMap{$0.deletedCategories}, failures: reports.flatMap{$0.failures}) }
    private func size(_ rel: String) -> Int64 { let u=root.appendingPathComponent(rel); guard let e = fm.enumerator(at: u, includingPropertiesForKeys: [.fileSizeKey]) else { return 0 }; return e.compactMap { ($0 as? URL).flatMap { try? $0.resourceValues(forKeys: [.fileSizeKey]).fileSize }.map(Int64.init) }.reduce(0,+) }
    private func countFiles(_ rel:String)->Int{ ((try? fm.contentsOfDirectory(atPath: root.appendingPathComponent(rel).path)) ?? []).count }
    private func countJSON(_ rel:String)->Int{ let url = root.appendingPathComponent(rel); guard let data = try? Data(contentsOf: url) else { return 0 }; if let array = try? JSONSerialization.jsonObject(with: data) as? [Any] { return array.count }; if let dict = try? JSONSerialization.jsonObject(with: data) as? [String: Any], let records = dict["records"] as? [Any] { return records.count }; return 0 }
    private func copyIfPresent(_ rel: String, to destination: URL, fallbackArrayWith encoder: JSONEncoder) throws { let src = root.appendingPathComponent(rel); if fm.fileExists(atPath: src.path) { try fm.copyItem(at: src, to: destination) } else { try encoder.encode([String]()).write(to: destination) } }
    private func currencyFavorites() -> [String] { (defaults.string(forKey: "currency.favoriteCodes") ?? "USD").split(separator: ",").map(String.init) }
    private func recentCurrencyPairs() -> [CurrencyPair] { (defaults.string(forKey: "currency.recentPairs") ?? "").split(separator: ",").compactMap { let parts = $0.split(separator: "-").map(String.init); return parts.count == 2 ? CurrencyPair(sourceCode: parts[0], destinationCode: parts[1]) : nil } }
    private func guideBookmarks() -> [GuideBookmark] { defaults.string(forKey: "guide.bookmarks")?.split(separator: ",").map { GuideBookmark(id: String($0), createdAt: Date(timeIntervalSince1970: 0)) } ?? [] }
    private func guideRecents() -> [RecentGuideItem] { defaults.string(forKey: "guide.recent")?.split(separator: "|").compactMap { item in let parts = item.split(separator: ":", maxSplits: 1).map(String.init); return parts.count == 2 ? RecentGuideItem(id: parts[0], title: parts[1], viewedAt: Date(timeIntervalSince1970: 0)) : nil } ?? [] }
}
