import Foundation
import UIKit

protocol AppDataExporting: Sendable { func createExport(includeRecoveryData: Bool) async throws -> URL }
protocol AppDataManaging: Sendable { func loadSummary() async throws -> AppDataSummary; func deleteReceipts() async -> DataDeletionReport; func deleteCalculations() async -> DataDeletionReport; func deleteSplits() async -> DataDeletionReport; func deleteNotes() async -> DataDeletionReport; func clearCurrencyCache() async -> DataDeletionReport; func clearCurrencyFavorites() async -> DataDeletionReport; func clearRecentCurrencyPairs() async -> DataDeletionReport; func clearGuideData() async -> DataDeletionReport; func resetPreferences() async -> DataDeletionReport; func resetOnboarding() async -> DataDeletionReport; func deleteMigrationMarkers() async -> DataDeletionReport; func deleteMigrationBackups() async -> DataDeletionReport; func deleteQuarantinedLegacyData() async -> DataDeletionReport; func deleteTemporaryAndRecoveryFiles() async -> DataDeletionReport; func deleteAllLocalData(includeRecoveryData: Bool) async -> DataDeletionReport }

enum DataCategory: String, Codable, Sendable { case receipts, calculations, splits, notes, currencyCache, currencyFavorites, recentCurrencyPairs, guideData, preferences, onboarding, migrationMarkers, migrationBackups, quarantine, temporaryAndRecoveryFiles }
struct DataDeletionFailure: Codable, Sendable, Hashable { var category: DataCategory; var message: String }
struct DataDeletionReport: Codable, Sendable { var deletedCategories: [DataCategory]; var failures: [DataDeletionFailure]; var completedFully: Bool { failures.isEmpty } }
struct AppDataSummary: Codable, Sendable { var receiptCount: Int; var calculationCount: Int; var splitCount: Int; var noteCount: Int; var guideBookmarkCount: Int; var favoriteCurrencyCount: Int; var recentCurrencyPairCount: Int; var cachedExchangeRateCount: Int; var receiptImageStorage: Int64; var totalAppDataStorage: Int64; var migrationBackupStorage: Int64; var quarantinedSourceCount: Int }
struct AppDataExportManifest: Codable, Sendable { var exportSchemaVersion: Int; var appVersion: String; var buildNumber: String; var exportDate: Date; var includedDataCategories: [String]; var recordCounts: [String:Int]; var missingOptionalImageFiles: [String]; var recoveryDataIncluded: Bool; var exportWarnings: [String] }

actor FileAppDataService: AppDataExporting, AppDataManaging {
    private let root: URL; private let fm: FileManager; private let receipts: ReceiptRepository; private let calculations: CalculationRepository; private let preferences: UserPreferencesRepository
    init(rootURL: URL? = nil, fileManager: FileManager = .default, receiptRepository: ReceiptRepository, calculationRepository: CalculationRepository, preferencesRepository: UserPreferencesRepository) { root = rootURL ?? fileManager.urls(for: .documentDirectory, in: .userDomainMask)[0]; fm = fileManager; receipts = receiptRepository; calculations = calculationRepository; preferences = preferencesRepository }
    func createExport(includeRecoveryData: Bool) async throws -> URL {
        let exportRoot = fm.temporaryDirectory.appendingPathComponent("TipsForTipsExport-\(UUID().uuidString)", isDirectory: true).appendingPathComponent("TipsForTipsExport", isDirectory: true)
        try fm.createDirectory(at: exportRoot, withIntermediateDirectories: true)
        let receiptRecords = try await receipts.fetchReceipts(); let calcRecords = try await calculations.fetchCalculations(); let prefs = try await preferences.loadPreferences()
        let enc = JSONEncoder(); enc.outputFormatting = [.prettyPrinted, .sortedKeys]; enc.dateEncodingStrategy = .iso8601
        try enc.encode(prefs).write(to: exportRoot.appendingPathComponent("preferences.json"))
        try enc.encode(receiptRecords).write(to: exportRoot.appendingPathComponent("receipts.json"))
        try enc.encode(calcRecords.filter { $0.tipResult != nil }).write(to: exportRoot.appendingPathComponent("calculations.json"))
        try enc.encode(calcRecords.filter { $0.splitResult != nil }).write(to: exportRoot.appendingPathComponent("saved-splits.json"))
        for name in ["notes","guide-bookmarks","guide-recents","currency-favorites","recent-currency-pairs","currency-cache"] { try Data("[]".utf8).write(to: exportRoot.appendingPathComponent("\(name).json")) }
        var missing: [String] = []
        let imageDir = exportRoot.appendingPathComponent("receipt-images", isDirectory: true), thumbDir = exportRoot.appendingPathComponent("receipt-thumbnails", isDirectory: true)
        try fm.createDirectory(at: imageDir, withIntermediateDirectories: true); try fm.createDirectory(at: thumbDir, withIntermediateDirectories: true)
        for r in receiptRecords { for (name,dir,srcDir) in [(r.imageFilename,imageDir,"Images"),(r.thumbnailFilename,thumbDir,"Thumbnails")] { guard let name else { continue }; let src = root.appendingPathComponent("V2/Receipts/\(srcDir)/\(name)"); if fm.fileExists(atPath: src.path) { try? fm.copyItem(at: src, to: dir.appendingPathComponent(name)) } else { missing.append(name) } } }
        if includeRecoveryData, fm.fileExists(atPath: root.appendingPathComponent("V2/Backups").path) { try? fm.copyItem(at: root.appendingPathComponent("V2/Backups"), to: exportRoot.appendingPathComponent("migration-recovery")) }
        let manifest = AppDataExportManifest(exportSchemaVersion: 1, appVersion: Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String ?? "Unknown", buildNumber: Bundle.main.object(forInfoDictionaryKey: "CFBundleVersion") as? String ?? "Unknown", exportDate: Date(), includedDataCategories: ["preferences","receipts","calculations","saved-splits","notes","guide","currency","receipt-images"], recordCounts: ["receipts": receiptRecords.count, "calculations": calcRecords.filter{$0.tipResult != nil}.count, "splits": calcRecords.filter{$0.splitResult != nil}.count], missingOptionalImageFiles: missing, recoveryDataIncluded: includeRecoveryData, exportWarnings: receiptRecords.flatMap { ReceiptFinancialReviewValidator().review($0).warnings }.isEmpty ? [] : ["Some receipts need financial charge review."])
        try enc.encode(manifest).write(to: exportRoot.appendingPathComponent("export-manifest.json")); return exportRoot
    }
    func loadSummary() async throws -> AppDataSummary { let rs = try await receipts.fetchReceipts(); let cs = try await calculations.fetchCalculations(); return AppDataSummary(receiptCount: rs.count, calculationCount: cs.filter{$0.tipResult != nil}.count, splitCount: cs.filter{$0.splitResult != nil}.count, noteCount: countJSON("Notes/notes.json"), guideBookmarkCount: 0, favoriteCurrencyCount: 0, recentCurrencyPairCount: 0, cachedExchangeRateCount: countJSON("V2/Currency/rates.json"), receiptImageStorage: size("V2/Receipts/Images") + size("V2/Receipts/Thumbnails"), totalAppDataStorage: size("V2"), migrationBackupStorage: size("V2/Backups"), quarantinedSourceCount: countFiles("V2/Backups/Quarantine")) }
    private func ok(_ c: DataCategory) -> DataDeletionReport { DataDeletionReport(deletedCategories: [c], failures: []) }
    private func remove(_ rel: String, _ c: DataCategory) -> DataDeletionReport { do { let u=root.appendingPathComponent(rel); if fm.fileExists(atPath:u.path){try fm.removeItem(at:u)}; return ok(c)} catch { return DataDeletionReport(deletedCategories: [], failures: [.init(category: c, message: error.localizedDescription)]) } }
    func deleteReceipts() async -> DataDeletionReport { for r in (try? await receipts.fetchReceipts()) ?? [] { try? await receipts.deleteReceipt(id: r.id) }; return ok(.receipts) }
    func deleteCalculations() async -> DataDeletionReport { for c in ((try? await calculations.fetchCalculations()) ?? []).filter({$0.tipResult != nil}) { try? await calculations.deleteCalculation(id: c.id) }; return ok(.calculations) }
    func deleteSplits() async -> DataDeletionReport { for c in ((try? await calculations.fetchCalculations()) ?? []).filter({$0.splitResult != nil}) { try? await calculations.deleteCalculation(id: c.id) }; return ok(.splits) }
    func deleteNotes() async -> DataDeletionReport { remove("Notes", .notes) }; func clearCurrencyCache() async -> DataDeletionReport { remove("V2/Currency/rates.json", .currencyCache) }; func clearCurrencyFavorites() async -> DataDeletionReport { ok(.currencyFavorites) }; func clearRecentCurrencyPairs() async -> DataDeletionReport { ok(.recentCurrencyPairs) }; func clearGuideData() async -> DataDeletionReport { ok(.guideData) }; func resetPreferences() async -> DataDeletionReport { try? await preferences.savePreferences(.defaults); return ok(.preferences) }; func resetOnboarding() async -> DataDeletionReport { try? await preferences.savePreferences(.defaults); return ok(.onboarding) }; func deleteMigrationMarkers() async -> DataDeletionReport { remove("V2/migration-v2-complete.json", .migrationMarkers) }; func deleteMigrationBackups() async -> DataDeletionReport { remove("V2/Backups", .migrationBackups) }; func deleteQuarantinedLegacyData() async -> DataDeletionReport { remove("V2/Backups/Quarantine", .quarantine) }; func deleteTemporaryAndRecoveryFiles() async -> DataDeletionReport { remove("V2/Receipts/Temporary", .temporaryAndRecoveryFiles) }
    func deleteAllLocalData(includeRecoveryData: Bool) async -> DataDeletionReport { var reports = [await deleteReceipts(), await deleteCalculations(), await deleteSplits(), await deleteNotes(), await clearCurrencyCache(), await clearCurrencyFavorites(), await clearRecentCurrencyPairs(), await clearGuideData(), await resetPreferences(), await resetOnboarding(), await deleteMigrationMarkers(), await deleteTemporaryAndRecoveryFiles()]; if includeRecoveryData { reports += [await deleteMigrationBackups(), await deleteQuarantinedLegacyData()] }; return DataDeletionReport(deletedCategories: reports.flatMap{$0.deletedCategories}, failures: reports.flatMap{$0.failures}) }
    private func size(_ rel: String) -> Int64 { let u=root.appendingPathComponent(rel); guard let e = fm.enumerator(at: u, includingPropertiesForKeys: [.fileSizeKey]) else { return 0 }; return e.compactMap { ($0 as? URL).flatMap { try? $0.resourceValues(forKeys: [.fileSizeKey]).fileSize }.map(Int64.init) }.reduce(0,+) }
    private func countFiles(_ rel:String)->Int{ ((try? fm.contentsOfDirectory(atPath: root.appendingPathComponent(rel).path)) ?? []).count }
    private func countJSON(_ rel:String)->Int{ 0 }
}
