import SwiftUI
import PhotosUI
import Vision
import AVFoundation
import UIKit

// MARK: - Scanner routing and state

enum ReceiptScannerContext: Hashable { case newReceipt, attachToCalculation(UUID), investigateGratuity, replaceImage(UUID) }
enum ReceiptScanStage: Equatable { case sourceSelection, capturing, processing, confirmation, saving, completed, failure }
enum ReceiptScannerPresentation: Identifiable { case camera; var id: String { "camera" } }

enum DetectionConfidence: String, Equatable { case high, medium, low
    init(_ value: Decimal) { self = value >= 0.78 ? .high : (value >= 0.5 ? .medium : .low) }
    var reviewText: String { self == .low ? "Please check this value" : (self == .medium ? "Review suggested value" : "Detected confidently") }
}

struct RecognizedTextObservation: Equatable, Hashable { var text: String; var confidence: Float; var boundingBox: CGRect; var candidates: [String] }
struct RecognizedReceiptText: Equatable, Hashable { var observations: [RecognizedTextObservation]; var fullText: String }
struct DetectedField<Value: Equatable>: Equatable { let value: Value; let confidence: Decimal; let sourceText: String }
enum ReceiptDetectionWarning: String, Equatable, Identifiable { case amountsDoNotAddUp, multipleTotals, serviceChargeMayNotBeGratuity, suggestedGratuityNotIncluded, receiptMayAlreadyContainGratuity, lowConfidenceFields; var id: String { rawValue }
    var message: String { switch self { case .amountsDoNotAddUp: return "The detected amounts do not add up to the total."; case .multipleTotals: return "More than one possible total was found."; case .serviceChargeMayNotBeGratuity: return "A service charge was found, but it may not be a gratuity."; case .suggestedGratuityNotIncluded: return "Suggested gratuity amounts were found and are not included in the total."; case .receiptMayAlreadyContainGratuity: return "The receipt may already contain gratuity."; case .lowConfidenceFields: return "Some detected values need review." } }
}
struct ReceiptDetectionResult: Equatable { var merchantCandidates: [DetectedField<String>] = []; var dateCandidates: [DetectedField<Date>] = []; var subtotalCandidates: [DetectedField<Decimal>] = []; var taxCandidates: [DetectedField<Decimal>] = []; var totalCandidates: [DetectedField<Decimal>] = []; var chargeCandidates: [DetectedReceiptCharge] = []; var currencyCandidates: [DetectedField<String>] = []; var warnings: [ReceiptDetectionWarning] = [] }

struct ProcessedReceiptImage { let fullImage: UIImage; let ocrImage: CGImage; let thumbnail: UIImage }

protocol ReceiptTextRecognizing { func recognizeText(in image: CGImage) async throws -> RecognizedReceiptText }
protocol ReceiptFieldParsing { func parse(recognizedText: RecognizedReceiptText, locale: Locale) -> ReceiptDetectionResult }

struct VisionReceiptTextRecognizer: ReceiptTextRecognizing {
    func recognizeText(in image: CGImage) async throws -> RecognizedReceiptText {
        try Task.checkCancellation()
        return try await Task.detached(priority: .userInitiated) {
            let request = VNRecognizeTextRequest(); request.recognitionLevel = .accurate; request.usesLanguageCorrection = true; request.recognitionLanguages = ["en-US"]
            let handler = VNImageRequestHandler(cgImage: image, options: [:]); try handler.perform([request]); try Task.checkCancellation()
            let observations = (request.results ?? []).compactMap { observation -> RecognizedTextObservation? in
                guard let top = observation.topCandidates(3).first else { return nil }
                return RecognizedTextObservation(text: top.string, confidence: top.confidence, boundingBox: observation.boundingBox, candidates: observation.topCandidates(3).map(\.string))
            }
            if observations.isEmpty { throw ReceiptScannerError.noTextFound }
            return RecognizedReceiptText(observations: observations, fullText: observations.map(\.text).joined(separator: "\n"))
        }.value
    }
}

enum ReceiptScannerError: LocalizedError { case cameraUnavailable, cameraDenied, imageLoadFailed, imageDecodeFailed, noTextFound, ocrFailed, saveFailed, invalidCalculationAmount
    var errorDescription: String? { switch self { case .cameraUnavailable: return "Camera is not available on this device. Choose a receipt from your photo library instead."; case .cameraDenied: return "Camera access is turned off. You can enable it in Settings or choose a receipt from your photo library."; case .imageLoadFailed: return "We could not load that receipt image. Try another photo or enter values manually."; case .imageDecodeFailed: return "We could not prepare that receipt image. Try another photo."; case .noTextFound, .ocrFailed: return "We couldn’t read all the details from this receipt. You can enter the values manually or try another photo."; case .saveFailed: return "We could not save this receipt. Please try again."; case .invalidCalculationAmount: return "Enter a valid subtotal or final total before continuing to the Tip Assistant." } }
}

struct ReceiptImageProcessor { static func process(_ image: UIImage) async throws -> ProcessedReceiptImage { try await Task.detached(priority: .userInitiated) { let normalized = image.normalizedForReceipt(); let full = normalized.resizedForReceipt(maxDimension: 2200); let ocr = normalized.resizedForReceipt(maxDimension: 1800); let thumb = normalized.resizedForReceipt(maxDimension: 420); guard let cg = ocr.cgImage else { throw ReceiptScannerError.imageDecodeFailed }; return ProcessedReceiptImage(fullImage: full, ocrImage: cg, thumbnail: thumb) }.value } }

struct ReceiptAmountParser { static func parse(_ text: String, locale: Locale = .current) -> Decimal? { var cleaned = text.replacingOccurrences(of: "USD", with: "", options: .caseInsensitive).replacingOccurrences(of: "$", with: "").replacingOccurrences(of: " ", with: ""); guard !cleaned.contains("%"), !cleaned.hasPrefix("-") else { return nil }; cleaned = cleaned.filter { "0123456789,.".contains($0) }; guard cleaned.count <= 10, cleaned.contains(".") || cleaned.contains(",") else { return nil }; if cleaned.filter({ $0 == "." }).count == 0, cleaned.filter({ $0 == "," }).count == 1 { cleaned = cleaned.replacingOccurrences(of: ",", with: ".") } else { cleaned = cleaned.replacingOccurrences(of: ",", with: "") }; return Decimal(string: cleaned, locale: Locale(identifier: "en_US_POSIX")) } }

struct ReceiptFieldParser: ReceiptFieldParsing {
    func parse(recognizedText: RecognizedReceiptText, locale: Locale = .current) -> ReceiptDetectionResult {
        let lines = recognizedText.observations.isEmpty ? recognizedText.fullText.split(separator: "\n").map { RecognizedTextObservation(text: String($0), confidence: 0.55, boundingBox: .zero, candidates: []) } : recognizedText.observations
        var result = ReceiptDetectionResult(); if recognizedText.fullText.contains("$") { result.currencyCandidates.append(.init(value: "USD", confidence: 0.7, sourceText: "$")) }
        detectMerchant(lines, &result); detectDates(lines, &result); detectAmounts(lines, &result); detectCharges(lines, &result); reconcile(&result); return result
    }
    private func detectMerchant(_ lines: [RecognizedTextObservation], _ result: inout ReceiptDetectionResult) { for line in lines.prefix(6) { let t = line.text.trimmingCharacters(in: .whitespaces); let lower = t.lowercased(); if t.count > 2 && !t.contains(where: { $0.isNumber }) && !lower.contains("receipt") && !lower.contains("tel") && !lower.contains("www") { result.merchantCandidates.append(.init(value: t, confidence: Decimal(Double(line.confidence)) * 0.9, sourceText: t)) } } }
    private func detectDates(_ lines: [RecognizedTextObservation], _ result: inout ReceiptDetectionResult) { let fmts = ["M/d/yyyy", "MM/dd/yyyy", "M/d/yy", "MM/dd/yy", "MMM d, yyyy", "MMM d yyyy"]; let formatter = DateFormatter(); formatter.locale = Locale(identifier: "en_US_POSIX"); for line in lines { guard !looksLikePhoneOrCard(line.text) else { continue }; for fmt in fmts { formatter.dateFormat = fmt; if let match = line.text.range(of: #"\b(?:\d{1,2}/\d{1,2}/\d{2,4}|[A-Za-z]{3}\s+\d{1,2},?\s+\d{4})\b"#, options: .regularExpression), let date = formatter.date(from: String(line.text[match])) { result.dateCandidates.append(.init(value: date, confidence: Decimal(Double(line.confidence)) * 0.85, sourceText: line.text)); break } } } }
    private func detectAmounts(_ lines: [RecognizedTextObservation], _ result: inout ReceiptDetectionResult) { for line in lines { let lower = line.text.lowercased(); guard let amount = lastAmount(in: line.text), !looksLikePhoneOrCard(line.text), !lower.contains("change"), !lower.contains("cash tender"), !lower.contains("auth") else { continue }; let conf = Decimal(Double(line.confidence)); if lower.contains("subtotal") || lower.contains("sub total") || lower.contains("net amount") { result.subtotalCandidates.append(.init(value: amount, confidence: conf * 0.95, sourceText: line.text)) } else if lower.contains("tax") && !lower.contains("tip") { result.taxCandidates.append(.init(value: amount, confidence: conf * 0.9, sourceText: line.text)) } else if (lower.contains("grand total") || lower.contains("amount due") || lower.contains("balance due") || lower.contains("check total") || lower == "total" || lower.hasPrefix("total ")) && !lower.contains("subtotal") && !lower.contains("suggest") { result.totalCandidates.append(.init(value: amount, confidence: conf * 0.95, sourceText: line.text)) } }
        if result.taxCandidates.count > 1 { let sum = result.taxCandidates.reduce(Decimal(0)) { $0 + $1.value }; result.taxCandidates.insert(.init(value: sum, confidence: 0.7, sourceText: "Combined tax lines"), at: 0) }
    }
    private func detectCharges(_ lines: [RecognizedTextObservation], _ result: inout ReceiptDetectionResult) { for line in lines { let lower = line.text.lowercased(); let kind: ReceiptChargeKind? = lower.contains("suggest") || lower.contains("tip guide") || lower.contains("gratuity guide") ? .suggestedGratuity : lower.contains("auto gratuity") || lower.contains("automatic gratuity") ? .automaticGratuity : lower.contains("included gratuity") || lower.contains("gratuity") ? .includedGratuity : lower.contains("hospitality") ? .hospitalityCharge : lower.contains("admin") ? .administrativeFee : lower.contains("delivery") ? .deliveryFee : lower.contains("service charge") ? .serviceCharge : nil; guard let kind else { continue }; let percent = percentAmount(in: line.text); let amount = lastAmount(in: line.text); result.chargeCandidates.append(DetectedReceiptCharge(label: line.text, amount: amount, percentage: percent, kind: kind, confidence: Decimal(Double(line.confidence)) * (kind == .suggestedGratuity ? 0.75 : 0.85), userClassification: nil)); if [.serviceCharge, .hospitalityCharge, .administrativeFee].contains(kind) { result.warnings.append(.serviceChargeMayNotBeGratuity) }; if kind == .suggestedGratuity { result.warnings.append(.suggestedGratuityNotIncluded) }; if kind == .includedGratuity || kind == .automaticGratuity { result.warnings.append(.receiptMayAlreadyContainGratuity) } }
    }
    private func reconcile(_ result: inout ReceiptDetectionResult) { if result.totalCandidates.count > 1 { result.warnings.append(.multipleTotals) }; if [result.merchantCandidates.first?.confidence, result.subtotalCandidates.first?.confidence, result.totalCandidates.first?.confidence].compactMap({ $0 }).contains(where: { $0 < 0.5 }) { result.warnings.append(.lowConfidenceFields) }; if let subtotal = result.subtotalCandidates.first?.value, let total = result.totalCandidates.first?.value { let tax = result.taxCandidates.first?.value ?? 0; let included = result.chargeCandidates.filter { [.includedGratuity, .automaticGratuity].contains($0.kind) }.compactMap(\.amount).reduce(0, +); let diff = abs(((subtotal + tax + included - total) as NSDecimalNumber).doubleValue); if diff > 0.05 { result.warnings.append(.amountsDoNotAddUp) } } }
    private func lastAmount(in text: String) -> Decimal? { let matches = text.matches(#"(?:USD\s*)?\$?\s*\d{1,3}(?:,\d{3})*(?:\.\d{2})|\$?\s*\d+\.\d{2}"#); return matches.compactMap { ReceiptAmountParser.parse($0) }.last }
    private func percentAmount(in text: String) -> Decimal? { text.matches(#"\d{1,2}(?:\.\d+)?\s*%"#).first.flatMap { Decimal(string: $0.replacingOccurrences(of: "%", with: "").trimmingCharacters(in: .whitespaces)) } }
    private func looksLikePhoneOrCard(_ text: String) -> Bool { let digits = text.filter(\.isNumber); return digits.count >= 10 && !text.contains(".") }
}

extension String { func matches(_ pattern: String) -> [String] { (try? NSRegularExpression(pattern: pattern)).map { regex in regex.matches(in: self, range: NSRange(startIndex..., in: self)).compactMap { Range($0.range, in: self).map { String(self[$0]) } } } ?? [] } }

struct ReceiptChargeDraft: Identifiable, Hashable { var id: UUID; var label: String; var amount: Decimal?; var percentage: Decimal?; var kind: ReceiptChargeKind; var confidence: Decimal; var userClassification: ReceiptChargeClassification }
struct ReceiptDraft: Identifiable { let id: UUID; var sourceImage: UIImage; var processed: ProcessedReceiptImage; var merchantName = ""; var receiptDate: Date?; var currencyCode = "USD"; var subtotalText = ""; var taxText = ""; var totalText = ""; var detectedCharges: [ReceiptChargeDraft] = []; var notes = ""; var recognizedText: String?; var warnings: [ReceiptDetectionWarning] = []; var hasUserEdits = false }

@MainActor final class ReceiptScannerViewModel: ObservableObject {
    @Published var stage: ReceiptScanStage = .sourceSelection; @Published var presentation: ReceiptScannerPresentation?; @Published var selectedPhoto: PhotosPickerItem?; @Published var draft: ReceiptDraft?; @Published var message: String?; @Published var savedReceiptID: UUID?; @Published var pendingTipInput: TipCalculationInput?; @Published var pendingTipReceiptID: UUID?; @Published var showUnsavedChanges = false; @Published var isSaving = false
    let context: ReceiptScannerContext; private let recognizer: ReceiptTextRecognizing; private let parser: ReceiptFieldParsing; private let store: ReceiptStore; private var processingTask: Task<Void, Never>?
    init(context: ReceiptScannerContext = .newReceipt, recognizer: ReceiptTextRecognizing = VisionReceiptTextRecognizer(), parser: ReceiptFieldParsing = ReceiptFieldParser(), store: ReceiptStore = ReceiptStore()) { self.context = context; self.recognizer = recognizer; self.parser = parser; self.store = store }
    func chooseCamera() { guard UIImagePickerController.isSourceTypeAvailable(.camera) else { message = ReceiptScannerError.cameraUnavailable.localizedDescription; return }; let status = AVCaptureDevice.authorizationStatus(for: .video); if status == .denied || status == .restricted { message = ReceiptScannerError.cameraDenied.localizedDescription; return }; presentation = .camera }
    func cameraCancelled() { presentation = nil; stage = .sourceSelection }
    func captured(_ image: UIImage) { presentation = nil; process(image) }
    func photoSelectionChanged(_ item: PhotosPickerItem?) { guard let item else { stage = .sourceSelection; return }; stage = .processing; Task { do { guard let data = try await item.loadTransferable(type: Data.self), let image = await Task.detached(priority: .userInitiated, operation: { UIImage(data: data) }).value else { throw ReceiptScannerError.imageLoadFailed }; process(image) } catch { message = ReceiptScannerError.imageLoadFailed.localizedDescription; stage = .sourceSelection } } }
    func process(_ image: UIImage) { processingTask?.cancel(); stage = .processing; processingTask = Task { do { let processed = try await ReceiptImageProcessor.process(image); let recognized = try await recognizer.recognizeText(in: processed.ocrImage); let detection = parser.parse(recognizedText: recognized, locale: .current); makeDraft(image: image, processed: processed, recognized: recognized, detection: detection) } catch is CancellationError { } catch { let processed = try? await ReceiptImageProcessor.process(image); if let processed { draft = ReceiptDraft(id: UUID(), sourceImage: image, processed: processed, recognizedText: nil, warnings: []); stage = .confirmation }; message = ReceiptScannerError.ocrFailed.localizedDescription } } }
    func cancelProcessing() { processingTask?.cancel(); stage = draft == nil ? .sourceSelection : .confirmation }
    private func makeDraft(image: UIImage, processed: ProcessedReceiptImage, recognized: RecognizedReceiptText, detection: ReceiptDetectionResult) { var d = ReceiptDraft(id: UUID(), sourceImage: image, processed: processed); d.merchantName = detection.merchantCandidates.first?.value ?? ""; d.receiptDate = detection.dateCandidates.first?.value; d.currencyCode = detection.currencyCandidates.first?.value ?? "USD"; d.subtotalText = detection.subtotalCandidates.first.map { "\($0.value)" } ?? ""; d.taxText = detection.taxCandidates.first.map { "\($0.value)" } ?? ""; d.totalText = detection.totalCandidates.first.map { "\($0.value)" } ?? ""; d.detectedCharges = detection.chargeCandidates.map { ReceiptChargeDraft(id: $0.id, label: $0.label, amount: $0.amount, percentage: $0.percentage, kind: $0.kind, confidence: $0.confidence, userClassification: defaultClassification(for: $0.kind)) }; d.recognizedText = recognized.fullText; d.warnings = detection.warnings; draft = d; stage = .confirmation }
    private func defaultClassification(for kind: ReceiptChargeKind) -> ReceiptChargeClassification { switch kind { case .includedGratuity, .automaticGratuity: return .includedGratuity; case .deliveryFee: return .deliveryFee; case .suggestedGratuity: return .suggestedGratuityOnly; case .serviceCharge, .hospitalityCharge, .administrativeFee: return .serviceChargeUnsure; default: return .otherOrUnclear } }
    func saveReceipt() async -> UUID? { guard !isSaving, let draft else { return savedReceiptID }; isSaving = true; stage = .saving; defer { isSaving = false }; do { let record = record(from: draft, id: savedReceiptID ?? draft.id); _ = try await store.save(record: record, fullImage: draft.processed.fullImage, thumbnail: draft.processed.thumbnail); savedReceiptID = record.id; stage = .completed; return record.id } catch { message = ReceiptScannerError.saveFailed.localizedDescription; stage = .confirmation; return nil } }
    func saveAndCalculate() { Task { if let id = await saveReceipt() { continueToAssistant(receiptID: id) } } }
    func continueToAssistant(receiptID: UUID? = nil) { guard let draft, let amount = ReceiptAmountParser.parse(draft.subtotalText).or(ReceiptAmountParser.parse(draft.totalText)) else { message = ReceiptScannerError.invalidCalculationAmount.localizedDescription; return }; var input = TipCalculationInput.defaults(); input.serviceID = "restaurant"; input.subtotal = ReceiptAmountParser.parse(draft.subtotalText); input.tax = ReceiptAmountParser.parse(draft.taxText); input.finalTotal = ReceiptAmountParser.parse(draft.totalText); input.currencyCode = draft.currencyCode.isEmpty ? "USD" : draft.currencyCode; input.calculationBasis = input.subtotal == nil ? .finalTotalAfterTax : .subtotalBeforeTax; let included = draft.detectedCharges.first { $0.userClassification == .includedGratuity }; let unsure = draft.detectedCharges.contains { $0.userClassification == .serviceChargeUnsure || $0.userClassification == .otherOrUnclear }; input.gratuityStatus = included != nil ? .yes : (unsure ? .unsure : .no); input.includedGratuityAmount = included?.amount; input.includedGratuityPercentage = included?.percentage; input.includedGratuityEntryMode = included?.amount != nil ? .amount : (included?.percentage != nil ? .percentage : .unknown); _ = amount; pendingTipReceiptID = receiptID; pendingTipInput = input }
    private func record(from draft: ReceiptDraft, id: UUID) -> ReceiptRecord { let now = Date(); return ReceiptRecord(id: id, merchantName: draft.merchantName.nilIfBlank, receiptDate: draft.receiptDate, currencyCode: draft.currencyCode, subtotal: ReceiptAmountParser.parse(draft.subtotalText), tax: ReceiptAmountParser.parse(draft.taxText), total: ReceiptAmountParser.parse(draft.totalText), detectedCharges: draft.detectedCharges.map { DetectedReceiptCharge(id: $0.id, label: $0.label, amount: $0.amount, percentage: $0.percentage, kind: $0.kind, confidence: $0.confidence, userClassification: $0.userClassification) }, imageFilename: "\(id.uuidString).jpg", thumbnailFilename: "\(id.uuidString)-thumb.jpg", recognizedText: draft.recognizedText, notes: draft.notes, confirmationStatus: .userConfirmed, createdAt: now, updatedAt: now) }
}

extension Optional where Wrapped == Decimal { func or(_ other: Decimal?) -> Decimal? { self ?? other } }
extension String { var nilIfBlank: String? { trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? nil : self } }

struct ReceiptScannerView: View { @StateObject private var model: ReceiptScannerViewModel; @State private var showFullImage = false; @Environment(\.dismiss) private var dismiss
    init(context: ReceiptScannerContext = .newReceipt, prefilledInput: TipCalculationInput? = nil) { _model = StateObject(wrappedValue: ReceiptScannerViewModel(context: context)) }
    var body: some View { AppScreen { content }.navigationTitle("Receipt Scanner").navigationBarTitleDisplayMode(.inline).toolbar { ToolbarItem(placement: .cancellationAction) { Button("Cancel") { if model.draft?.hasUserEdits == true || model.draft != nil { model.showUnsavedChanges = true } else { dismiss() } } } }.sheet(item: $model.presentation) { _ in ReceiptCameraView(onCapture: model.captured, onCancel: model.cameraCancelled, onFailure: { model.message = $0.localizedDescription; model.cameraCancelled() }) }.onChange(of: model.selectedPhoto) { model.photoSelectionChanged($0) }.alert("Receipt Scanner", isPresented: Binding(get: { model.message != nil }, set: { if !$0 { model.message = nil } })) { Button("OK", role: .cancel) {} } message: { Text(model.message ?? "") }.alert("Unsaved receipt", isPresented: $model.showUnsavedChanges) { Button("Save Receipt") { Task { _ = await model.saveReceipt(); dismiss() } }; Button("Discard", role: .destructive) { dismiss() }; Button("Keep Editing", role: .cancel) {} } message: { Text("Save this receipt before leaving, discard it, or keep editing.") }.navigationDestination(isPresented: Binding(get: { model.pendingTipInput != nil }, set: { _ in })) { GuidedTipAssistantView(prefilledInput: model.pendingTipInput, linkedReceiptID: model.pendingTipReceiptID) } }
    @ViewBuilder private var content: some View { switch model.stage { case .sourceSelection: source; case .processing: processing; case .confirmation, .saving, .completed, .failure: confirmation; case .capturing: source } }
    private var source: some View { ScrollView { VStack(spacing: AppSpacing.section) { ScreenTitle(text: "Scan Receipt", subtitle: "Photos and recognized text stay on this device. OCR suggestions must be reviewed before calculating."); ThemedCard { PrimaryButton(title: "Take Photo", systemImage: "camera") { model.chooseCamera() }; PhotosPicker(selection: $model.selectedPhoto, matching: .images) { Label("Choose from Photo Library", systemImage: "photo").appFont(.h3).frame(maxWidth: .infinity, minHeight: 44) }.buttonStyle(AppButtonStylePublic.secondary).accessibilityLabel("Choose receipt from photo library"); SecondaryButton(title: "Enter Values Manually", systemImage: "square.and.pencil") { model.stage = .confirmation } }; privacy }.padding(AppSpacing.screen) } }
    private var privacy: some View { ThemedCard { Text("Privacy").appFont(.h2); Text("Text recognition uses Apple Vision on-device. Receipt images and optional recognized text are saved locally only; no receipt content is sent to currency services or analytics.").appFont(.paragraph) } }
    private var processing: some View { VStack(spacing: AppSpacing.section) { if let image = model.draft?.sourceImage { Image(uiImage: image).resizable().scaledToFit().frame(maxHeight: 260).accessibilityLabel("Selected receipt image") }; LoadingStateView(message: "Reading receipt…").accessibilityLabel("Reading receipt"); SecondaryButton(title: "Cancel Reading") { model.cancelProcessing() } }.padding(AppSpacing.screen) }
    private var confirmation: some View { ReceiptConfirmationView(model: model) }
}

struct ReceiptConfirmationView: View { @ObservedObject var model: ReceiptScannerViewModel; @State private var showImage = false
    var body: some View { ScrollView { VStack(spacing: AppSpacing.section) { ScreenTitle(text: "Review Receipt", subtitle: "Every value is editable. Suggested gratuity is informational and is not treated as paid."); if model.draft != nil { let draft = Binding<ReceiptDraft>(get: { model.draft! }, set: { model.draft = $0 }); imageSection(draft); details(draft); amounts(draft); charges(draft); warnings(draft); actions } else { manualStart } }.padding(AppSpacing.screen) }.hideKeyboardToolbar().fullScreenCover(isPresented: $showImage) { if let image = model.draft?.sourceImage { NavigationStack { AppScreen { Image(uiImage: image).resizable().scaledToFit().padding().accessibilityLabel("Full screen receipt image") }.toolbar { Button("Done") { showImage = false } } } } } }
    private var manualStart: some View { ThemedCard { Text("No image selected").appFont(.h2); Text("Choose a receipt image to attach, or go back and select camera or photo library.").appFont(.paragraph) } }
    private func imageSection(_ draft: Binding<ReceiptDraft>) -> some View { ThemedCard { Image(uiImage: draft.wrappedValue.sourceImage).resizable().scaledToFit().frame(maxHeight: 260).clipShape(RoundedRectangle(cornerRadius: 14)).accessibilityLabel("Receipt image preview"); HStack { Button("View") { showImage = true }; Button("Retake") { model.chooseCamera() }; PhotosPicker(selection: $model.selectedPhoto, matching: .images) { Text("Replace") } }.appFont(.paragraph).foregroundStyle(AppTheme.accent) } }
    private func details(_ draft: Binding<ReceiptDraft>) -> some View { ThemedCard { Text("Merchant and date").appFont(.h2); TextField("Merchant name", text: draft.merchantName).textFieldStyle(AppTextFieldStyle()).accessibilityLabel("Merchant name"); DatePicker("Receipt date", selection: Binding(get: { draft.wrappedValue.receiptDate ?? Date() }, set: { draft.wrappedValue.receiptDate = $0; draft.wrappedValue.hasUserEdits = true }), displayedComponents: .date); Button("Clear date") { draft.wrappedValue.receiptDate = nil }; TextField("Currency code", text: draft.currencyCode).textFieldStyle(AppTextFieldStyle()).textInputAutocapitalization(.characters) } }
    private func amounts(_ draft: Binding<ReceiptDraft>) -> some View { ThemedCard { Text("Amounts").appFont(.h2); TextField("Subtotal", text: draft.subtotalText).keyboardType(.decimalPad).textFieldStyle(AppTextFieldStyle()); TextField("Tax", text: draft.taxText).keyboardType(.decimalPad).textFieldStyle(AppTextFieldStyle()); TextField("Total", text: draft.totalText).keyboardType(.decimalPad).textFieldStyle(AppTextFieldStyle()); Text("Low-confidence or missing values can be corrected before calculating.").appFont(.paragraph).foregroundStyle(AppTheme.text.opacity(0.75)) } }
    private func charges(_ draft: Binding<ReceiptDraft>) -> some View { ThemedCard { Text("Charges and gratuity").appFont(.h2); if draft.detectedCharges.isEmpty { Text("No gratuity or service-charge wording was detected. You can still calculate manually.").appFont(.paragraph) }; ForEach(draft.detectedCharges) { $charge in VStack(alignment: .leading, spacing: AppSpacing.small) { Text(charge.label).appFont(.h3); Text(charge.kind.explanation).appFont(.paragraph); Picker("Classification", selection: $charge.userClassification) { ForEach(ReceiptChargeClassification.allCases) { Text($0.title).tag($0) } }.pickerStyle(.menu).accessibilityLabel("Classification for \(charge.label)"); if DetectionConfidence(charge.confidence) != .high { Label(DetectionConfidence(charge.confidence).reviewText, systemImage: "exclamationmark.triangle").appFont(.paragraph).foregroundStyle(AppTheme.highlight) } }.padding(.vertical, 6) }; TextField("Notes", text: draft.notes, axis: .vertical).textFieldStyle(AppTextFieldStyle()) } }
    private func warnings(_ draft: Binding<ReceiptDraft>) -> some View { Group { if !draft.wrappedValue.warnings.isEmpty { ThemedCard { Text("Review notes").appFont(.h2); ForEach(draft.wrappedValue.warnings) { warning in Label(warning.message, systemImage: "exclamationmark.triangle").appFont(.paragraph).foregroundStyle(AppTheme.highlight) } } } } }
    private var actions: some View { ThemedCard { PrimaryButton(title: "Continue to Tip Assistant", systemImage: "sparkles") { model.continueToAssistant() }; PrimaryButton(title: model.isSaving ? "Saving…" : "Save Receipt", systemImage: "checkmark", isDisabled: model.isSaving) { Task { _ = await model.saveReceipt() } }; SecondaryButton(title: "Save and Calculate", systemImage: "arrow.right", isDisabled: model.isSaving) { model.saveAndCalculate() }; SecondaryButton(title: "Enter Values Manually", systemImage: "square.and.pencil") { model.message = "Edit any field above. OCR is optional." }; SecondaryButton(title: "Rescan", systemImage: "camera") { model.chooseCamera() } } }
}

struct ReceiptCameraView: UIViewControllerRepresentable { let onCapture: (UIImage) -> Void; let onCancel: () -> Void; let onFailure: (Error) -> Void
    func makeUIViewController(context: Context) -> UIImagePickerController { let picker = UIImagePickerController(); guard UIImagePickerController.isSourceTypeAvailable(.camera) else { DispatchQueue.main.async { onFailure(ReceiptScannerError.cameraUnavailable) }; return picker }; picker.sourceType = .camera; picker.delegate = context.coordinator; return picker }
    func updateUIViewController(_ uiViewController: UIImagePickerController, context: Context) {}
    func makeCoordinator() -> Coordinator { Coordinator(onCapture: onCapture, onCancel: onCancel, onFailure: onFailure) }
    final class Coordinator: NSObject, UINavigationControllerDelegate, UIImagePickerControllerDelegate { let onCapture: (UIImage) -> Void; let onCancel: () -> Void; let onFailure: (Error) -> Void; init(onCapture: @escaping (UIImage) -> Void, onCancel: @escaping () -> Void, onFailure: @escaping (Error) -> Void) { self.onCapture = onCapture; self.onCancel = onCancel; self.onFailure = onFailure }
        func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey: Any]) { guard let image = info[.originalImage] as? UIImage else { picker.dismiss(animated: true) { self.onFailure(ReceiptScannerError.imageLoadFailed) }; return }; picker.dismiss(animated: true) { self.onCapture(image) } }
        func imagePickerControllerDidCancel(_ picker: UIImagePickerController) { picker.dismiss(animated: true) { self.onCancel() } }
    }
}

extension ReceiptChargeKind { var explanation: String { switch self { case .includedGratuity, .automaticGratuity: return "May already be included in the bill."; case .serviceCharge, .hospitalityCharge, .administrativeFee: return "May not be the same as a voluntary tip; confirm before counting it."; case .deliveryFee: return "Do not assume this is a driver tip."; case .suggestedGratuity: return "Informational suggestion only, not already paid."; default: return "Review this charge." } } }
